sudo: false
language: ruby
cache: bundler
rvm:
  - ruby-2.4.2
  - ruby-2.4.1
  - ruby-2.4.0
  - ruby-2.4.0-rc1
  - ruby-2.4.0-preview3
  - ruby-2.4.0-preview2
  - ruby-2.4.0-preview1
  - ruby-2.3.5
  - ruby-2.3.4
  - ruby-2.3.3
  - ruby-2.3.2
  - ruby-2.3.1
  - ruby-2.3.0
  - ruby-2.3.0-preview2
  - ruby-2.3.0-preview1
  - ruby-2.2.8
  - ruby-2.2.7
  - ruby-2.2.6
  - ruby-2.2.5
  - ruby-2.2.4
  - ruby-2.2.3
  - ruby-2.2.2
  - ruby-2.2.1
  - ruby-2.1.10
  - ruby-2.1.9
  - ruby-2.1.8
  - ruby-2.1.7
  - ruby-2.1.6
  - ruby-2.1.5
  - ruby-2.1.4
  - ruby-2.1.3
  - ruby-2.1.2
  - ruby-2.1.0
  - ruby-2.0.0-p648
  - ruby-2.0.0-p647
  - ruby-2.0.0-p645
  - jruby-head
  - jruby-9.1.9.0
  - jruby-9.1.5.0
  - jruby-9.1.4.0
  - jruby-9.1.3.0
  - jruby-9.1.2.0
  - jruby-9.1.1.0
  - jruby-9.1.0.0
  - jruby-9.0.5.0
  - jruby-9.0.4.0
  - jruby-9.0.3.0
  - jruby-9.0.1.0
  - jruby-9.0.0.0
  - jruby-1.7.26
  - jruby-1.7.25
  - jruby-1.7.24
  - jruby-1.7.23
  - jruby-1.7.22

before_install: gem install bundler -v 1.7.6
